---
- name: install epel repository
  yum_repository:
    name: epel
    description: EPEL Yum Repository from HEANET
    state: present
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_repo_gpg_key_url }}"
    gpgcheck: yes
    enabled: yes    
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
